### ISSUE TITLE
Float the header XX pixels down the page

### ISSUE THREAD

**Issue by shackrock** [laertejjunior/freezeheader#15]
For my use, I have a static menu bar which is always at the top of the page.  I need the header to show up below that, ~100px lower.  Is there an easy way to adjust for this in the js file to compensate, and have it's starting point 100px lower?

Additionally, it should be "triggered" to start (show up) 100px sooner as well - as the true header gets hidden 100px sooner.

Thanks.

**Comment by shackrock** [comment]
This seems to simply move the table header row below the static menu bar, but it doesn't "activate" the freezeHeader any earlier while scrolling.

**Comment by laertejjunior** [comment]
I applied a patch. you can verify?

**Comment by shackrock** [comment]
Just tried it out.  I experience no change in behavior after applying the new code, and using the call with the offset option as you suggested.

**Comment by laertejjunior** [comment]
[example.zip](https://github.com/laertejjunior/freezeheader/files/681356/example.zip)

**Comment by laertejjunior** [comment]
[example.zip](https://github.com/laertejjunior/freezeheader/files/681357/example.zip)

**Comment by shackrock** [comment]
Well that works perfectly, so I must have a conflict with my bootstrap theme.  I'll do some research, thanks.
