### ISSUE TITLE
Thead overlaps with content after table.

### ISSUE THREAD

**Issue by Dudatemp56** [laertejjunior/freezeheader#25]
If table head is bigger than tbody cells. then it keep overlap with contents after table , even  we reached at the end of table. (see attached) 

![1](https://user-images.githubusercontent.com/119395366/204455588-7939681e-83fc-4088-b3f4-36097a8ba9c0.jpg)
![2](https://user-images.githubusercontent.com/119395366/204455601-43d83607-a1be-4199-8e94-5cfcf0b2c0d7.jpg)

in my case table header is 4x bigger than columns. and it overlaps with content placed after table. even scrolled to end of table.

**Comment by Dudatemp56** [comment]
Please help me fix it.

**Comment by laertejjunior** [comment]
Got it, I'll look into it.

**Comment by Dudatemp56** [comment]
To see the issue, table head height must be larger than table body columns. Then you will see that issue. 

Hoping soon it will get fixed. 

Good luck 🤞
